spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ppd
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  tomcat:
    max-swallow-size: 2MB